#! /usr/bin/env python

import sferes


def build(bld):


    sferes.create_variants(bld,
		source='obstacle_avoidance.cpp',
                uselib_local = 'sferes2 fastsim  ',
                uselib = 'EIGEN3 SDL BOOST_GRAPH BOOST_THREAD TBB ROS',
                target = 'obstacle_avoidance',
                cxxflags = bld.get_env()['CXXFLAGS'] + ['-Wno-unknown-pragmas'],
                json = 'obstacle_avoidance.json',
                variants = [
                                 'ENVOA1 NO_PARALLEL',
                                 'ENVOA1',
                ])

