#! /usr/bin/env python

import sferes
import os
import Options

def set_options(opt):
    opt.add_option('--cafer', type='string', help='path to cafer_core install directory.', dest='cafer')


def configure(conf):
    cafer_path='/usr/local'
    if Options.options.cafer:
        cafer_path=Options.options.cafer

    conf.env['CPPPATH_CAFER'] = cafer_path + '/include/'
    conf.env['LIBPATH_CAFER'] = cafer_path + '/lib'
    conf.env['LIB_CAFER'] = ['cafer_core']

def build(bld):
    pass

    # print ("Entering directory `" + os.getcwd() + "/modules/'")
    # uselib = 'BOOST'
    # cafer_fastsim = bld.new_task_gen('cxx', 'staticlib')
    # cafer_fastsim.source = 'cafer_fastsim.cpp'
    # cafer_fastsim.includes = '. ../../'
    # cafer_fastsim.target = 'cafer_fastsim'
    # cafer_fastsim.uselib = 'BOOST'



